"""menambah kolom status di tabel transaksi

Revision ID: 2415b66da3f1
Revises: 54ae504e4338
Create Date: 2024-12-27 18:43:33.444195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2415b66da3f1'
down_revision = '54ae504e4338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_peminjaman', sa.Enum('Dengan Supir', 'Lepas Kunci'), nullable=False))
        batch_op.add_column(sa.Column('status_transaksi', sa.Enum('Selesai', 'Pending'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.drop_column('status_transaksi')
        batch_op.drop_column('status_peminjaman')

    # ### end Alembic commands ###
